### ISSUE TITLE
Error at steam url

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/MoEmbed#69]
e.g.) http://store.steampowered.com/app/648100/

```
web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
web_1  |       Request starting HTTP/1.1 GET http://embed.kokoro.io/api?url=http%3A%2F%2Fstore.steampowered.com%2Fapp%2F648100%2F&format=xml  
web_1  | info: MoEmbed.HttpMetadataHandler[0]
web_1  |       Handling URL: http://store.steampowered.com/app/648100/
web_1  | info: MoEmbed.HttpMetadataHandler[0]
web_1  |       An exception thrown: System.IndexOutOfRangeException: Index was outside the bounds of the array.
web_1  |          at Shipwreck.OpenGraph.PropertyPath.StartsWith(PropertyPath property, String path, Boolean& matched, Boolean skipCompareProperty)
web_1  |          at Shipwreck.OpenGraph.GraphObject.<>c__DisplayClass105_0.<GetLocalProperty>b__0(PropertyEntry kv)
web_1  |          at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
web_1  |          at Shipwreck.OpenGraph.GraphObject.GetLocalProperty(String property)
web_1  |          at MoEmbed.Models.Metadata.UnknownMetadata.LoadHtml(HtmlDocument htmlDocument) in /usr/src/MoEmbed.Core/Models/Metadata/UnknownMetadata.cs:line 236
web_1  |          at MoEmbed.Models.Metadata.UnknownMetadata.<FetchAsyncCore>d__39.MoveNext() in /usr/src/MoEmbed.Core/Models/Metadata/UnknownMetadata.cs:line 158
web_1  |       --- End of stack trace from previous location where exception was thrown ---
web_1  |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1  |          at MoEmbed.Models.Metadata.UnknownMetadata.<FetchAsyncCore>d__39.MoveNext() in /usr/src/MoEmbed.Core/Models/Metadata/UnknownMetadata.cs:line 203
web_1  |       --- End of stack trace from previous location where exception was thrown ---
web_1  |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1  |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |          at MoEmbed.MetadataService.<GetDataAsync>d__6.MoveNext() in /usr/src/MoEmbed.Core/MetadataService.cs:line 62
web_1  |       --- End of stack trace from previous location where exception was thrown ---
web_1  |          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
web_1  |          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
web_1  |          at MoEmbed.HttpMetadataHandler.<HandleAsync>d__4.MoveNext() in /usr/src/MoEmbed.Core/HttpMetadataHandler.cs:line 69
web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
web_1  |       Request finished in 4.7732ms 404 text/xml
```

**Comment by pgrho** [comment]
https://github.com/pgrho/open-graph/issues/8
