### ISSUE TITLE
Build fails on heroku

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/MoEmbed#94]
```
-----> ASP.NET Core app detected
Installing dotnet
-----> Removing old cached .NET version
-----> Fetching .NET SDK
-----> Fetching .NET Runtime
publish /tmp/build_2d4ce4c9089f8cc9809985786f683b9a/MoEmbed.CodeGeneration/MoEmbed.CodeGeneration.csproj for Release
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restore completed in 3.25 sec for /tmp/build_2d4ce4c9089f8cc9809985786f683b9a/MoEmbed.CodeGeneration/MoEmbed.CodeGeneration.csproj.
  Restore completed in 4.89 sec for /tmp/build_2d4ce4c9089f8cc9809985786f683b9a/MoEmbed.CodeGeneration/MoEmbed.CodeGeneration.csproj.
  System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/build_2d4ce4c9089f8cc9809985786f683b9a/oembed/providers'.
     at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
     at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
     at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
     at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
     at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
     at System.IO.Directory.GetFiles(String path, String searchPattern)
     at Submission#0.<<Initialize>>d__0.MoveNext() in /tmp/build_2d4ce4c9089f8cc9809985786f683b9a/MoEmbed.CodeGeneration/OEmbedProxyMetadataProviders.csx:line 27
  --- End of stack trace from previous location where exception was thrown ---
     at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs)
/tmp/build_2d4ce4c9089f8cc9809985786f683b9a/MoEmbed.CodeGeneration/MoEmbed.CodeGeneration.csproj(22,5): error MSB3073: The command "dotnet script OEmbedProxyMetadataProviders.csx" exited with code 1.
 !     Push rejected, failed to compile ASP.NET Core app.
 !     Push failed
```

**Comment by supermomonga** [comment]
It seems heroku automated build will ignore submodules.

**Comment by supermomonga** [comment]
https://devcenter.heroku.com/articles/github-integration-review-apps#do-git-submodules-work
