### ISSUE TITLE
YouTube URL での失敗

### ISSUE THREAD

**Issue by supermomonga** [supermomonga/MoEmbed#97]
```
2020-06-14T10:35:49.916277+00:00 heroku[router]: at=info method=GET path="/api?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFwBMBsRJoPA&format=json" host=moembed.herokuapp.com request_id=4ebd31f4-9c49-48b9-b0ff-743761c2198f fwd="217.178.17.77" dyno=web.1 connect=0ms service=7ms status=404 bytes=204 protocol=http
2020-06-14T10:35:49.916447+00:00 app[web.1]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
2020-06-14T10:35:49.916456+00:00 app[web.1]: Request starting HTTP/1.1 GET http://moembed.herokuapp.com/api?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFwBMBsRJoPA&format=json
2020-06-14T10:35:49.916457+00:00 app[web.1]: info: MoEmbed.HttpMetadataHandler[0]
2020-06-14T10:35:49.916457+00:00 app[web.1]: Handling URL: https://www.youtube.com/watch?v=FwBMBsRJoPA(null)
2020-06-14T10:35:49.919807+00:00 app[web.1]: info: MoEmbed.HttpMetadataHandler[0]
2020-06-14T10:35:49.919837+00:00 app[web.1]: An exception thrown: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 429 (Too Many Requests).)
2020-06-14T10:35:49.919838+00:00 app[web.1]: ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
2020-06-14T10:35:49.919839+00:00 app[web.1]: at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2020-06-14T10:35:49.919846+00:00 app[web.1]: at MoEmbed.Models.Metadata.UnknownMetadata.FetchOnceAsync(RequestContext context) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/Models/Metadata/UnknownMetadata.cs:line 105
2020-06-14T10:35:49.919847+00:00 app[web.1]: at MoEmbed.Models.RequestContextExtensions.ExecuteAsync(RequestContext context, Func`2 func) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/Models/RequestContextExtensions.cs:line 24
2020-06-14T10:35:49.919848+00:00 app[web.1]: at MoEmbed.Models.RequestContextExtensions.ExecuteAsync(RequestContext context, Func`2 func) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/Models/RequestContextExtensions.cs:line 40
2020-06-14T10:35:49.919848+00:00 app[web.1]: --- End of inner exception stack trace ---
2020-06-14T10:35:49.919849+00:00 app[web.1]: at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2020-06-14T10:35:49.919849+00:00 app[web.1]: at MoEmbed.Models.Metadata.UnknownMetadata.<FetchAsyncCore>b__15_0(Task`1 t) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/Models/Metadata/UnknownMetadata.cs:line 90
2020-06-14T10:35:49.919850+00:00 app[web.1]: at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
2020-06-14T10:35:49.919850+00:00 app[web.1]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2020-06-14T10:35:49.919851+00:00 app[web.1]: --- End of stack trace from previous location where exception was thrown ---
2020-06-14T10:35:49.919851+00:00 app[web.1]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-06-14T10:35:49.919851+00:00 app[web.1]: --- End of stack trace from previous location where exception was thrown ---
2020-06-14T10:35:49.919852+00:00 app[web.1]: at MoEmbed.MetadataService.GetDataAsync(ConsumerRequest request) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/MetadataService.cs:line 135
2020-06-14T10:35:49.919852+00:00 app[web.1]: at MoEmbed.HttpMetadataHandler.HandleAsync(HttpContext context) in /tmp/build_d1fbc0c8cc8ce3bab1dc5d37224111ea/MoEmbed.Core/HttpMetadataHandler.cs:line 122
2020-06-14T10:35:49.919853+00:00 app[web.1]: info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2020-06-14T10:35:49.919853+00:00 app[web.1]: Request finished in 2.5369ms 404 application/json
```

**Comment by supermomonga** [comment]
ローカルでは再現せず
